### ISSUE TITLE
Data Is Not Available Anymore

### ISSUE THREAD

**Issue by Jeklah** [neurotroph/BVM-DataScienceCup-2017#2]
Wasn't really sure where else to put this...
The dataset for the BVM Data Science Cup 2017 isn't up at the link you provided anymore....I don't suppose you still have this data set do you? If so could you possibly upload it?

**Comment by neurotroph** [comment]
As the data was not mine, I don't think I can post it. If you are interested, you could reach out to the BVM who organised the Data Science Cup: https://www.bvm.org/der-bvm/data-science-cup/
